-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 10:47:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ereputation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ereputation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ereputation` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `ereputation` ;

-- -----------------------------------------------------
-- Table `ereputation`.`ecommerces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ereputation`.`ecommerces` (
  `idecommerce` INT(11) NOT NULL AUTO_INCREMENT,
  `ecommercename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idecommerce`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ereputation`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ereputation`.`commandes` (
  `idcommande` INT(11) NOT NULL AUTO_INCREMENT,
  `ecommerces_idecommerce` INT(11) NULL DEFAULT NULL,
  `commandeclient` VARCHAR(45) NOT NULL,
  `commandedate` DATE NOT NULL,
  `commandeprix` VARCHAR(45) NOT NULL,
  `commandequantite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcommande`),
  CONSTRAINT `FK_35D4282C54CD4CB7`
    FOREIGN KEY (`ecommerces_idecommerce`)
    REFERENCES `ereputation`.`ecommerces` (`idecommerce`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_commandes_ecommerces1` ON `ereputation`.`commandes` (`ecommerces_idecommerce` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ereputation`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ereputation`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `userfirstname` VARCHAR(45) NULL DEFAULT NULL,
  `userlastname` VARCHAR(45) NULL DEFAULT NULL,
  `useremail` VARCHAR(45) NULL DEFAULT NULL,
  `userpassword` VARCHAR(45) NOT NULL,
  `userlogin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ereputation`.`connectionecommerce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ereputation`.`connectionecommerce` (
  `idconnection` INT(11) NOT NULL AUTO_INCREMENT,
  `ecommerces_idecommerce` INT(11) NULL DEFAULT NULL,
  `user_iduser` INT(11) NULL DEFAULT NULL,
  `connectionlogin` VARCHAR(45) NOT NULL,
  `connectionpassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconnection`),
  CONSTRAINT `FK_A2F6CC213B0E3CD4`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `ereputation`.`user` (`iduser`),
  CONSTRAINT `FK_A2F6CC2154CD4CB7`
    FOREIGN KEY (`ecommerces_idecommerce`)
    REFERENCES `ereputation`.`ecommerces` (`idecommerce`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_connectionecommerce_ecommerces1` ON `ereputation`.`connectionecommerce` (`ecommerces_idecommerce` ASC) VISIBLE;

CREATE INDEX `fk_connectionecommerce_user1` ON `ereputation`.`connectionecommerce` (`user_iduser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ereputation`.`socialnetworks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ereputation`.`socialnetworks` (
  `idsocialnetwork` INT(11) NOT NULL AUTO_INCREMENT,
  `socialnetworkname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsocialnetwork`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ereputation`.`connectionsocialnetwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ereputation`.`connectionsocialnetwork` (
  `idconnection` INT(11) NOT NULL AUTO_INCREMENT,
  `socialnetworks_idsocialnetwork` INT(11) NULL DEFAULT NULL,
  `user_iduser` INT(11) NULL DEFAULT NULL,
  `connectionlogin` VARCHAR(45) NOT NULL,
  `connectionpassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconnection`),
  CONSTRAINT `FK_698E0E913B0E3CD4`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `ereputation`.`user` (`iduser`),
  CONSTRAINT `FK_698E0E916704F91B`
    FOREIGN KEY (`socialnetworks_idsocialnetwork`)
    REFERENCES `ereputation`.`socialnetworks` (`idsocialnetwork`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_connection_socialnetworks1` ON `ereputation`.`connectionsocialnetwork` (`socialnetworks_idsocialnetwork` ASC) VISIBLE;

CREATE INDEX `fk_connection_user1` ON `ereputation`.`connectionsocialnetwork` (`user_iduser` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
